name: Test Erlang
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ["24.0.2", "23.3.4.2", "22.3.4.20"]
        rebar3_version: ["3.16.1"]
        os: [ubuntu-latest]
        include:
          - otp_version: "21.3.8.24"
            rebar3_version: "3.15.2"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          rebar3-version: ${{ matrix.rebar3_version }}
      - run: "rebar3 --version"
      - run: "rebar3 compile"
